[package]
name = "wrangler"
version = "1.6.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "wrangle your workers, CLI for rustwasm Cloudflare workers!"
readme = "README.md"
repository = "https://github.com/cloudflare/wrangler"
categories = ["wasm", "development-tools", "command-line-utilities", "web-programming"]
build = "build.rs"

[dependencies]
atty = "0.2.11"
base64 = "0.10.1"
binary-install = "0.0.3-alpha"
clap = "2.32.0"
cloudflare = "0.4.1"
config = "0.9.2"
console = "0.7.5"
data-encoding = "2.1.2"
dirs = "1.0.5"
env_logger = "0.6.1"
exitfailure = "0.5.1"
failure = "0.1.5"
flate2 = "1.0.7"
fs2 = "0.4.3"
http = "0.1.1"
ignore = "0.4.10"
indicatif = "0.13.0"
lazy_static = "1.3.0"
log = "0.4.6"
notify = "4.0.12"
number_prefix = "0.3.0"
openssl = { version = '0.10.11', optional = true }
percent-encoding = "1.0.1"
prettytable-rs = "0.8.0"
rand = "0.6.5"
regex = "1"
reqwest = "0.9.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
sha2 = "0.8.0"
tempfile = "3.1.0"
text_io = "0.1.7"
toml = "0.5.5"
url = "2.1.0"
uuid = "0.7"
which = "2.0.1"
ws = "0.9.0"

[dev-dependencies]
assert_cmd = "0.11.1"
fs_extra = "1.1.0"

[features]
vendored-openssl = ['openssl/vendored']
